# Generated by Django 5.2.3 on 2025-08-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Kupac'), ('seller', 'Prodavac')], default='buyer', max_length=10),
        ),
    ]
